### ISSUE TITLE
Please add an example!

### ISSUE THREAD

**Issue by UlrichEckhardt** [jbelien/phpstan-sarif-formatter#26]
Hi!

I'm trying to integrate GitHub and PHPStan using your extension, but it doesn't seem to work well. What I get is the scans uploaded and also displayed in a list, but nothing like the comments in the merge request linked by the README. I think it would really help if you had a branch that just adds an issue plus an according PR to really see the thing in action.

BTW: I'm also wondering whether I need to enable some feature for my GitHub project and also whether I first have to implement scanning in the default (main or master) branch and not just in the target branch for a PR. If one of these things are necessary, then that part is missing from the README.

Thanks for your work!

Uli

**Comment by UlrichEckhardt** [comment]
Update: I think I found out why it doesn't work:
```yaml
...
jobs:
  run-phpstan:
    permissions:
      # for github/codeql-action/upload-sarif to upload SARIF results
      security-events: write
    ...
```

Allowing the job to write security events is mandatory. It will still happily scan the code and even upload the results, but they won't be integrated into the UI during pull requests.
